# Generated by Django 3.2.8 on 2023-07-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
