# Generated by Django 3.2.8 on 2023-07-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_transaction_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_id',
            field=models.CharField(max_length=20),
        ),
    ]
